version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: stylelint-declaration-strict-value
    versions:
    - 1.7.10
    - 1.7.7
    - 1.7.9
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: "@trigen/scripts-plugin-eslint"
    versions:
    - 7.0.6
    - 7.3.3
  - dependency-name: "@trigen/scripts-preset-lib"
    versions:
    - 7.0.6
    - 7.3.3
  - dependency-name: "@trigen/scripts"
    versions:
    - 7.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: stylelint-scss
    versions:
    - 3.18.0
